### ISSUE TITLE
Moving structopt to clap (clap_derive)

### ISSUE THREAD

**Issue by theredfish** [cucumber-rs/cucumber#155]
Clap recently introduced [clap_derive](https://github.com/clap-rs/clap/tree/master/clap_derive) . Would it be ok if I propose a new PR to integrate the changes and move to it?

structop is using clap behind the scene and will be [soft-deprecated](https://github.com/clap-rs/clap/blob/master/FAQ.md#how-does-clap-compare-to-structopt) in favor of clap_derive.

Before proposing a new PR for this I just want to know if this change is ok for you?

**Comment by tyranron** [comment]
@theredfish we've [used `clap`](https://github.com/cucumber-rs/cucumber/blob/354112097a389c4949e42433f02364d054df0f28/Cargo.toml#L35), but [intentionally have switched to `structopt`](https://github.com/cucumber-rs/cucumber/pull/144), because at the moment of out investigation `clap_derive` lacked support for flattening over type parameters, which we're using to make our CLI composable.

We're going to switch back to `clap` once it supports that feature.

If you'd like to drive that feature in upstream and then propose a PR here, we would be happy about that!

**Comment by theredfish** [comment]
Oh ok yes definitely! I will keep you updated 👍

**Comment by ilslv** [comment]
`structopt`-like generics support just got [merged], so it looks like we can migrate to `clap v3.0.0-beta.6` once it gets released. 



[merged]: https://github.com/clap-rs/clap/pull/3023

**Comment by tyranron** [comment]
@ilslv [`3.0.0-rc.1` has been released](https://docs.rs/clap/3.0.0-rc.1/clap/index.html)

**Comment by theredfish** [comment]
Do you plan to make the update ? I'm still available to make the update if you want. Let me know

**Comment by tyranron** [comment]
@theredfish as we've said before, we would love to see a PR. So, go ahead!
